# mongodb secrets
apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
type: Opaque
data:
  mongodb-root-username: dXNlcm5hbWU= # base-64 encoded "username"
  mongodb-root-password: cGFzc3dvcmQ= # base-64 encoded "password"

---

# scout secrets
apiVersion: v1
kind: Secret
metadata:
  name: scout-secret
type: Opaque
data:
  scout-username: c2NvdXRVc2Vy # base-64 encoded "scoutUser"
  scout-password: c2NvdXRQYXNzd29yZA== # base-64 encoded "scoutPassword"
