version: '3'
# usage:
# (sudo) docker-compose up -d
# (sudo) docker-compose down
services:

  mongodb:
    image: mvertes/alpine-mongo
    container_name: mongodb
    ports:
      - '27017:27017'
    expose:
      - '27017'
    networks:
      - scout-net

  scout-cli:
    build: .
    container_name: scout-cli
    command: bash -c "
      scout --host mongodb setup demo
      && scout --host mongodb --demo load case scout/demo/cancer.load_config.yaml"
    volumes:
      - ./scout:/home/worker/app/scout
      - ./volumes/scout/data:/home/worker/data
    networks:
      - scout-net
    depends_on:
      - mongodb

  scout-web:
    build: .
    container_name: scout-web
    expose:
      - '5000'
    ports:
      - '5000:5000'
    command: bash -c "
      scout --host mongodb --demo serve --host 0.0.0.0
      && npm i webpack --save-dev
      && npm i webpack-cli --save-dev
      && npm i @babel/core --save-dev
      && npm i babel-loader --save-dev
      && npm i @babel/preset-env --save-dev
      && npm i @babel/preset-react --save-dev
      && npm run watch --prefix /home/worker/app/scout/scout/server/static"

    volumes:
      - ./scout:/home/worker/app/scout
      - ./volumes/scout/data:/home/worker/data
    networks:
      - scout-net
    depends_on:
      - mongodb

networks:
  scout-net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.21.0.0/24
