# usage:
# (sudo) docker-compose up -d
# (sudo) docker-compose down
services:

  mongodb:
    image: mongo:7
    container_name: mongodb
    networks:
      - scout-net
    ports:
      - '27017:27017'
    expose:
      - '27017'

  scout-cli:
    build: .
    platform: linux/amd64
    container_name: scout-cli
    command: ["--host", "mongodb", "setup", "demo"]
    volumes:
      - ./scout:/home/worker/app/scout
    networks:
      - scout-net
    depends_on:
      - mongodb

  scout-web:
    build:
      context: .
      dockerfile: Dockerfile-server
    platform: linux/amd64
    expose:
      - '8000'
    ports:
      - '8000:8000'
    environment:
      SCOUT_CONFIG: /home/worker/app/scout/server/config.py
      MONGO_HOST: mongodb
      MONGO_DBNAME: scout-demo
      GUNICORN_WORKERS: 1
      GUNICORN_TREADS: 1
      GUNICORN_BIND: 0.0.0.0:8000
      GUNICORN_TIMEOUT: 400
    volumes:
      - ./scout:/home/worker/app/scout
    networks:
      - scout-net
    depends_on:
      - mongodb

networks:
  scout-net:
    driver: bridge
