version: '3'
# usage:
# (sudo) docker-compose up -d
# (sudo) docker-compose down
services:

  mongodb:
    image: mongo:4.4.9
    container_name: mongodb
    networks:
      - scout-net
    ports:
      - '27013:27017'
    expose:
      - '27017'

  scout-cli:
    build: .
    container_name: scout-cli
    command: bash -c "
      scout --host mongodb setup demo
      && scout --host mongodb --demo load case scout/demo/cancer.load_config.yaml"
    volumes:
      - ./scout:/home/worker/app/scout
      - ./volumes/scout/data:/home/worker/data
    networks:
      - scout-net
    depends_on:
      - mongodb

  scout-web:
    build: .
    container_name: scout-web
    expose:
      - '5000'
    ports:
      - '5000:5000'
    command: scout --host mongodb --demo serve --host 0.0.0.0
    volumes:
      - ./scout:/home/worker/app/scout
      - ./volumes/scout/data:/home/worker/data
    networks:
      - scout-net
    depends_on:
      - mongodb

networks:
  scout-net:
    driver: bridge
