version: '3'
# usage:
# (sudo) docker-compose up -d
# (sudo) docker-compose down
services:

  mongodb:
    image: mvertes/alpine-mongo
    container_name: mongodb
    ports:
      - '27017:27017'
    expose:
      - '27017'
    networks:
      - scout-net

  scout-cli:
    image: clinicalgenomics/scout
    container_name: scout-cli
    command: scout --host mongodb setup demo
    volumes:
      - ./scout:/home/worker/app/scout
      - ./volumes/scout/data:/home/worker/data
    networks:
      - scout-net
    depends_on:
      - mongodb

  scout-web:
    image: clinicalgenomics/scout
    container_name: scout-web
    expose:
      - '5000'
    ports:
      - '5000:5000'
    command: scout --host mongodb --demo serve --host 0.0.0.0
    volumes:
      - ./scout:/home/worker/app/scout
      - ./volumes/scout/data:/home/worker/data
    networks:
      - scout-net
    depends_on:
      - mongodb

networks:
  scout-net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.21.0.0/24
