version: '3'
# usage:
# (sudo) docker-compose up -d
# (sudo) docker-compose down
services:

  mongodb:
    image: mvertes/alpine-mongo
    container_name: mongodb
    ports:
      - '27017:27017'
    expose:
      - '27017'
    networks:
      - scout-net

  scout-cli:
    image: clinicalgenomics/scout
    container_name: scout-cli
    command: bash -c "
      scout --host mongodb setup demo
      && scout --host mongodb --demo load case scout/demo/cancer.load_config.yaml"
    volumes:
      - ./scout:/home/worker/app/scout
      - ./volumes/scout/data:/home/worker/data
    networks:
      - scout-net
    depends_on:
      - mongodb

  scout-web:
    image: clinicalgenomics/scout
    container_name: scout-web
    expose:
      - '5000'
    ports:
      - '5000:5000'
    command: scout --host mongodb --demo serve --host 0.0.0.0
    volumes:
      - ./scout:/home/worker/app/scout
      - ./volumes/scout/data:/home/worker/data
    networks:
      - scout-net
    depends_on:
      - mongodb
      - mariadb

  mariadb:
    image: mariadb:latest
    environment:
     - MYSQL_ROOT_PASSWORD=root
     - MYSQL_USER=chanjoUser
     - MYSQL_PASSWORD=chanjoPassword
     - MYSQL_DATABASE=chanjo
    volumes:
     - ./volumes/mariadb/data:/var/lib/mysql
    healthcheck: # Wait for the service to be ready before accepting incoming connections
        test: "mysql --user=chanjoUser --password=chanjoPassword --execute \"SHOW DATABASES;\""
        timeout: 10s
        retries: 20
    networks:
     - scout-net
    restart: unless-stopped

  chanjo-cli:
    image: clinicalgenomics/scout
    environment:
     - SQLALCHEMY_DATABASE_URI=mysql+pymysql://chanjoUser@mariadb?password=chanjoPassword&db=chanjo
    depends_on:
      - mariadb
    volumes:
     - ./volumes/chanjo/data:/data/data
    networks:
     - scout-net
    restart: unless-stopped

networks:
  scout-net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.30.0.0/24
