# HOWTO:
# In: scout/server/config.py
# ADD:
# LDAP_HOST = "openldap"
# LDAP_PORT = 10389
# LDAP_BASE_DN = "dc=planetexpress,dc=com"
# LDAP_USER_DN = "ou=people"
# LDAP_USER_LOGIN_ATTR = "mail"

# Move this file under the main scout folder (at the same level of Dockerfile)
# docker-compose -f docker-compose-LDAP.yml up

# Login into Scout using LDAP as Leela (username:leela@planetexpress.com, password:leela)

# docker-compose down

version: '3'

services:

  mongodb:
    image: mongo:4.4.9
    container_name: mongodb
    networks:
      - scout-net
    ports:
      - '27013:27017'
    expose:
      - '27017'

  openldap:
    image: rroemhild/test-openldap # https://github.com/rroemhild/docker-test-openldap
    ports:
      - '10389:10389'
      - '10636:10636'
    networks:
      - scout-net

  scout-web:
    build: .
    container_name: scout-web
    expose:
      - '5000'
    ports:
      - '5000:5000'
    command: bash -c '
      scout --host mongodb setup demo
      && scout --host mongodb --demo load user -i cust000 -u "Leela Turanga" -m leela@planetexpress.com -id leela@planetexpress.com
      && scout --host mongodb --demo serve --host 0.0.0.0'
    volumes:
      - ./scout:/home/worker/app/scout
      - ./volumes/scout/data:/home/worker/data
    depends_on:
      - mongodb
      - openldap
    networks:
      - scout-net

networks:
  scout-net:
    driver: bridge
