# Deployment document for Scout web server
apiVersion: apps/v1
kind: Deployment
metadata:
  name: scout-web
  labels:
    app: scout-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: scout-web
  template:
    metadata:
      labels:
        app: scout-web
    spec:
      containers:
      - name: scout-web
        image: clinicalgenomics/scout
        ports:
        - containerPort: 5000
        env:
        - name: flask-config
          value: /Users/chiararasi/Documents/work/GITs/scout/container/k8s-configuration/scout-config.yaml
        command: ["scout", "--host", "mongodb-service", "serve", "--host", "0.0.0.0"]

---
# External service document
apiVersion: v1
kind: Service
metadata:
  name: scout-web-service
spec:
  selector:
    app: scout-web
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 30000
