export const getMockCases = {
  cases: {
    search_terms: {
      case: { label: 'Case or individual name', prefix: 'case:' },
      exact_pheno: { label: 'HPO term', prefix: 'exact_pheno:' },
      synopsis: { label: 'Search synopsis', prefix: 'synopsis:' },
      panel: { label: 'Gene panel', prefix: 'panel:' },
      status: { label: 'Case status', prefix: 'status:' },
      track: { label: 'Analysis track', prefix: 'track:' },
      pheno_group: { label: 'Phenotype group', prefix: 'pheno_group:' },
      cohort: { label: 'Patient cohort', prefix: 'cohort:' },
      'Similar case': { label: 'Similar case', prefix: 'similar_case:' },
      similar_pheno: { label: 'Similar phenotype', prefix: 'similar_pheno:' },
      pinned: { label: 'Pinned gene', prefix: 'pinned:' },
      causative: { label: 'Causative gene', prefix: 'causative:' },
      user: { label: 'Assigned user', prefix: 'user:' },
    },
    institute: {
      _id: 'cust000',
      internal_id: 'cust000',
      display_name: 'cust000',
      sanger_recipients: ['clark.kent@mail.com'],
      created_at: '2021-07-14T12:55:58.343000',
      updated_at: '2021-07-14T12:55:58.343000',
      coverage_cutoff: 10,
      frequency_cutoff: 0.01,
      cohorts: ['pedhep', 'mito'],
    },
    name_query: null,
    form: {
      meta: null,
      _prefix: '',
      _fields: {
        search_type: null,
        search_term: null,
        search_limit: null,
        skip_assigned: null,
        is_research: null,
        search: null,
        csrf_token: null,
      },
      _csrf: { meta: null },
      search_type: null,
      search_term: null,
      search_limit: null,
      skip_assigned: null,
      is_research: null,
      search: null,
      csrf_token: null,
    },
    skip_assigned: null,
    is_research: null,
    sort_order: 'asc',
    sort_by: null,
    nr_cases: 2,
    cases: [
      ['prioritized', []],
      [
        'inactive',
        [
          {
            _id: 'cancer_test',
            display_name: 'cancer_case',
            owner: 'cust000',
            collaborators: ['cust000'],
            smn_tsv: null,
            individuals: [
              {
                individual_id: '999-99',
                display_name: '999-99',
                sex: '1',
                phenotype: 2,
                bam_file: null,
                mt_bam: '/home/worker/app/scout/demo/reduced_mt.bam',
                rna_coverage_bigwig: null,
                tiddit_coverage_wig: null,
                rhocall_bed: null,
                rhocall_wig: null,
                splice_junctions_bed: null,
                upd_regions_bed: null,
                upd_sites_bed: null,
                vcf2cytosure: null,
                father: null,
                mother: null,
                capture_kits: ['Twist.V1'],
                confirmed_sex: null,
                confirmed_parent: null,
                predicted_ancestry: null,
                chromograph_images: null,
                analysis_type: 'panel',
                tmb: 7,
                msi: 15,
                tumor_purity: 1,
                tumor_type: 'Chordoma',
                tissue_type: 'unknown',
                is_sma: null,
                is_sma_carrier: null,
                smn1_cn: null,
                smn2_cn: null,
                smn2delta78_cn: null,
                smn_27134_cn: null,
              },
              {
                individual_id: '998-99',
                display_name: '998-99',
                sex: '1',
                phenotype: 1,
                bam_file: null,
                mt_bam: '/home/worker/app/scout/demo/reduced_mt.bam',
                rna_coverage_bigwig: null,
                tiddit_coverage_wig: null,
                rhocall_bed: null,
                rhocall_wig: null,
                splice_junctions_bed: null,
                upd_regions_bed: null,
                upd_sites_bed: null,
                vcf2cytosure: null,
                father: null,
                mother: null,
                capture_kits: ['Twist.V1'],
                confirmed_sex: null,
                confirmed_parent: null,
                predicted_ancestry: null,
                chromograph_images: null,
                analysis_type: 'panel',
                tissue_type: 'unknown',
                is_sma: null,
                is_sma_carrier: null,
                smn1_cn: null,
                smn2_cn: null,
                smn2delta78_cn: null,
                smn_27134_cn: null,
              },
            ],
            created_at: '2021-07-14T12:56:28.802000',
            updated_at: '2021-07-14T12:56:28.802000',
            synopsis: null,
            status: 'inactive',
            is_research: false,
            research_requested: false,
            rerun_requested: false,
            lims_id: null,
            analysis_date: '2018-10-12T14:00:46',
            panels: [],
            dynamic_gene_list: [],
            genome_build: 37,
            rank_model_version: '1.1',
            rank_score_threshold: -100.0,
            madeline_info: null,
            chromograph_image_files: null,
            chromograph_prefixes: null,
            multiqc: null,
            cnv_report: 'scout/demo/cancer_cnv_report.pdf',
            coverage_qc_report: 'scout/demo/cancer_coverage_qc_report.html',
            gene_fusion_report: null,
            gene_fusion_report_research: null,
            vcf_files: {
              vcf_snv: null,
              vcf_sv: null,
              vcf_str: null,
              vcf_cancer: 'scout/demo/cancer_test.vcf.gz',
              vcf_cancer_sv: 'scout/demo/manta_vep_94_annotated_sv_cancer_file.vcf.gz',
              vcf_snv_research: null,
              vcf_sv_research: null,
              vcf_cancer_research: null,
              vcf_cancer_sv_research: null,
            },
            delivery_report: 'scout/demo/delivery_report.html',
            has_svvariants: false,
            has_strvariants: false,
            is_migrated: false,
            track: 'cancer',
            group: [],
            analysis_types: ['panel'],
            assignees: [],
            is_rerun: [],
            clinvar_variants: {},
            display_track: 'Cancer',
          },
          {
            _id: 'internal_id',
            display_name: '643594',
            owner: 'cust000',
            collaborators: ['cust000'],
            smn_tsv: 'scout/demo/643594.solo.smn.tsv',
            individuals: [
              {
                individual_id: 'ADM1059A2',
                display_name: 'NA12882',
                sex: '1',
                phenotype: 2,
                bam_file: null,
                mt_bam: '/home/worker/app/scout/demo/reduced_mt.bam',
                rna_coverage_bigwig:
                  '/home/worker/app/scout/demo/ACC5963A1_lanes_1234_star_sorted_sj_filtered.bigWig',
                tiddit_coverage_wig: null,
                rhocall_bed: null,
                rhocall_wig: null,
                splice_junctions_bed:
                  '/home/worker/app/scout/demo/ACC5963A1_lanes_1234_star_sorted_sj_filtered_sorted.bed.gz',
                upd_regions_bed: null,
                upd_sites_bed: null,
                vcf2cytosure: '/home/worker/app/scout/demo/ADM1059A2.test.cgh',
                father: 'ADM1059A1',
                mother: 'ADM1059A3',
                capture_kits: ['Agilent_SureSelectCRE.V1'],
                confirmed_sex: true,
                confirmed_parent: null,
                predicted_ancestry: 'EUR',
                chromograph_images: {
                  autozygous: 'scout/demo/images/chromograph_demo/autozygous_regions',
                  coverage: 'scout/demo/images/chromograph_demo/coverage',
                  upd_regions: 'scout/demo/images/chromograph_demo/upd_regions',
                  upd_sites: 'scout/demo/images/chromograph_demo/upd_sites',
                },
                analysis_type: 'wes',
                tissue_type: 'blood',
                is_sma: false,
                is_sma_carrier: null,
                smn1_cn: 2,
                smn2_cn: 0,
                smn2delta78_cn: 0,
                smn_27134_cn: 0,
              },
              {
                individual_id: 'ADM1059A1',
                display_name: 'NA12877',
                sex: '1',
                phenotype: 1,
                bam_file: null,
                mt_bam: '/home/worker/app/scout/demo/reduced_mt.bam',
                rna_coverage_bigwig: null,
                tiddit_coverage_wig: null,
                rhocall_bed: null,
                rhocall_wig: null,
                splice_junctions_bed: null,
                upd_regions_bed: null,
                upd_sites_bed: null,
                vcf2cytosure: '/home/worker/app/scout/demo/ADM1059A1.test.cgh',
                father: '0',
                mother: '0',
                capture_kits: ['Agilent_SureSelectCRE.V1'],
                confirmed_sex: true,
                confirmed_parent: true,
                predicted_ancestry: 'EUR',
                chromograph_images: null,
                analysis_type: 'wes',
                tissue_type: 'blood',
                is_sma: null,
                is_sma_carrier: null,
                smn1_cn: null,
                smn2_cn: null,
                smn2delta78_cn: null,
                smn_27134_cn: null,
              },
              {
                individual_id: 'ADM1059A3',
                display_name: 'NA12878',
                sex: '2',
                phenotype: 1,
                bam_file: null,
                mt_bam: '/home/worker/app/scout/demo/reduced_mt.bam',
                rna_coverage_bigwig: null,
                tiddit_coverage_wig: null,
                rhocall_bed: null,
                rhocall_wig: null,
                splice_junctions_bed: null,
                upd_regions_bed: null,
                upd_sites_bed: null,
                vcf2cytosure: '/home/worker/app/scout/demo/ADM1059A3.test.cgh',
                father: '0',
                mother: '0',
                capture_kits: ['Agilent_SureSelectCRE.V1'],
                confirmed_sex: true,
                confirmed_parent: true,
                predicted_ancestry: 'EUR',
                chromograph_images: null,
                analysis_type: 'wes',
                tissue_type: 'blood',
                is_sma: null,
                is_sma_carrier: null,
                smn1_cn: null,
                smn2_cn: null,
                smn2delta78_cn: null,
                smn_27134_cn: null,
              },
            ],
            created_at: '2021-07-14T12:56:13.221000',
            updated_at: '2021-07-14T12:56:13.221000',
            synopsis:
              'Test case consisting of an affected male individual. Both parents are unaffected',
            status: 'inactive',
            is_research: false,
            research_requested: false,
            rerun_requested: false,
            lims_id: 'LID1234',
            analysis_date: '2016-10-12T14:00:46',
            panels: [
              {
                panel_id: '60eedeed6eb20936daef5866',
                panel_name: 'panel1',
                display_name: 'Test panel',
                version: 1.0,
                updated_at: '2021-07-14T12:56:02.503000',
                nr_genes: 263,
                is_default: true,
              },
            ],
            dynamic_gene_list: [],
            genome_build: 37,
            rank_model_version: '1.20',
            sv_rank_model_version: '1.5',
            rank_score_threshold: -100.0,
            cohorts: ['pedhep', 'mito'],
            phenotype_terms: [
              { phenotype_id: 'HP:0001298', feature: 'Encephalopathy' },
              { phenotype_id: 'HP:0001250', feature: 'Seizures' },
            ],
            madeline_info:
              '<?xml version="1.0" standalone="no"?>\n <svg version="1.1"  id="svgDC" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink"  width="279.72" height="266.884"  onload="init()" >\n <defs>\n  <style type="text/css"><![CDATA[\n\nline{\n\tstroke:#000;\n\tstroke-width:0.5mm;\n\tstroke-linejoin:miter;\n\tstroke-linecap:square;\n}\n\nrect{\n\tstroke:#000;\n\tstroke-width:0.5mm;\n\tstroke-linejoin:miter;\n\tstroke-linecap:square;\n}\n\nellipse{\n\tstroke: #000;\n    fill: #fff;\n\tstroke-width:0.25mm;\n}\n\ntext{\n\tfont-family:"DejaVu Sans",sans-serif;\n\tfont-size:12px;\n}\n\n.smallText{\n\tfont-family:"DejaVu Sans",sans-serif;\n\tfont-size:9px;\n\tfill:#444;\n}\n\n.layer text{\n\tfill:#930;\n}\n\n.layer line{\n\tstroke:#000;\n}\n\n.birthOrder,.unknownTwins{\n\tfont-size: 8px;\n}\n\n.header{\n\tfont-size:18px;\n\tfont-weight:bold;\n}\n\n.keyBox{\n\tfill:#e5e5e5;\n\tstroke:#000;\n\tstroke-width:0.5mm;\n\tstroke-linejoin:miter;\n\tstroke-linecap:square;\n}\n\n.mating:hover{\n\tstroke-width:1mm;\n\tstroke:#d56300;\n}\n\n.selectedIndividual{\n\tstroke-width:1mm;\n\tstroke-linecap:square;\n\tstroke-linejoin:miter;\n\tstroke:#d00;\n    fill:none;\n}\n\n.selectedIndividual:hover{\n\tstroke:#d00;\n\tfill:#ffbbbb;\n\tfill-opacity:0.70;\n}\n\n.solid{\n\tstroke-width:0.5mm;\n\tstroke-linecap:square;\n\tstroke-linejoin:miter;\n\tstroke:#000;\n\tfill:none;\n}\n\n.dashed{\n\tstroke-width:0.5mm;\n\tstroke-linecap:square;\n\tstroke-linejoin:miter;\n\tstroke:#98afc7;\n\tstroke-dasharray:2mm,1mm;\n\tstroke-dashoffset:1.0mm;\n\tfill:none;\n}\n\n.solid:hover{\n\tfill:#ffb787;\n\tfill-opacity:0.70;\n\tstroke:#d56300;\n\tstroke-width:1mm;\n}\n\n.dashed:hover{\n\tfill:#ffb787;\n\tfill-opacity:0.70;\n\tstroke:#d56300;\n\tstroke-width:1mm;\n}\n\n.filled{\n\tstroke-width:0.5mm;\n\tstroke-linecap:square;\n\tstroke-linejoin:miter;\n\tstroke:#000;\n\tfill:#000;\n}\n\n.specialIcons{\n\tstroke-width:0.25mm;\n\tstroke-linecap:round;\n\tstroke-linejoin:miter;\n\tstroke:#000;\n\tfill:#fff;\n}\n\n.specialLines{\n\tstroke-linecap:square;\n\tstroke-linejoin:miter;\n\tstroke:#000;\n\tstroke-width:0.5mm;\n\tfill:none;\n}\n\n.thinLine{\n\tfill:none;\n\tstroke: #000;\n\tstroke-width:0.25mm;\n}\n\n.curvedConnector{\n\tstroke-linecap:square;\n\tstroke-linejoin:miter;\n\tstroke:#98afc7;\n\tstroke-width:0.5mm;\n\tstroke-dasharray:2mm,1mm;\n\tstroke-dashoffset:1.0mm;\n\tfill:none;\n}\n\n.curvedConnector:hover{\n\tstroke:#d56300;\n}\n\n.whiteInkLetter_1{\n\tfont-size: 12px;\n\tfill: #fff;\n}\n\n.whiteInkLetter_2{\n\tfont-size: 10px;\n\tfill: #fff;\n}\n\n.whiteInkLetter_3{\n\tfont-size: 8px;\n\tfill: #fff;\n}\n\n.whiteInkLetter{\n\tfont-size: 8px;\n\tfill: #fff;\n}\n\n.blackInkLetter_1{\n\tfont-size: 12px;\n}\n\n.blackInkLetter_2{\n\tfont-size: 10px;\n}\n\n.blackInkLetter_3{\n\tfont-size: 8px;\n}\n\n.blackInkLetter{\n\tfont-size: 8px;\n\tfill: #000;\n}\n\n]]></style>\n <script type="text/javascript" xlink:href="javascript/madeline.js"></script>\n <marker id="endArrow" viewBox="0 0 10 10" refX="1" refY="5" markerUnits="strokeWidth" orient="auto" markerWidth="5" markerHeight="4">  <polyline points="0,0 10,5 0,10 1,5" fill="#000" /> </marker>\n </defs>\n <g class="pedigree" transform="translate(-372.14)">\n\n <g id="bottomLayer" class="layer" >\n\n </g>\n <g id="layer0" class="layer" >\n </g>\n\n  <g class="drawing">\n  <text x="557.36" y="30" text-anchor="middle"  class="header" >643594</text>\n  <clipPath id="ADM1059A1_clipPath">\n   <rect x="500.66" y="38.66" width="22.68" height="22.68" />\n  </clipPath>\n<g clip-path="url(#ADM1059A1_clipPath)">\n<circle cx="512" cy="50" r="16.0372" style="fill:#ffd802;stroke:none;"/>\n  <text x="512" y="54.3588" text-anchor="middle"  class="blackInkLetter_1" >U</text>\n</g>\n  <rect x="500.66" y="38.66" width="22.68" height="22.68" id="ADM1059A1" class="solid">\n\t<title>ADM1059A1</title>\n</rect>\n  <text x="512" y="92.5845" text-anchor="middle" >ADM1059A1</text>\n  <line x1="523.34" y1="50" x2="591.38" y2="50" />\n<g>\n<circle cx="602.72" cy="50" r="11.34" style="fill:#ffd802;stroke:none;"/>\n  <text x="602.72" y="54.3588" text-anchor="middle"  class="blackInkLetter_1" >U</text>\n</g>\n<circle cx="602.72" cy="50" r="11.34" id="ADM1059A3" class="solid">\n\t<title>ADM1059A3</title>\n</circle>\n  <text x="602.72" y="92.5845" text-anchor="middle" >ADM1059A3</text>\n  <line class="mating" id="ADM1059A3:ADM1059A1" x1="557.36" y1="50" x2="557.36" y2="123.907" />\n  <line class="solid" x1="557.36" y1="123.907" x2="557.36" y2="152.257" />\n  <clipPath id="ADM1059A2_clipPath">\n   <rect x="546.02" y="152.257" width="22.68" height="22.68" />\n  </clipPath>\n<g clip-path="url(#ADM1059A2_clipPath)">\n<circle cx="557.36" cy="163.597" r="16.0372" style="fill:#0000a0;stroke:none;"/>\n  <text x="557.36" y="167.956" text-anchor="middle"  class="whiteInkLetter_1" >A</text>\n</g>\n  <rect x="546.02" y="152.257" width="22.68" height="22.68" id="ADM1059A2" class="solid">\n\t<title>ADM1059A2</title>\n</rect>\n  <text x="557.36" y="206.181" text-anchor="middle" >ADM1059A2</text>\n  </g>\n  <g class="legend">\n  <text x="421.28" y="50" text-anchor="middle" >Affected</text>\n  <rect  x="379.7" y="53.78" width="83.16" height="18.3356" style="fill:#0000a0;"  />\n  <text x="421.28" y="67.5123" text-anchor="middle"  class="whiteInkLetter_1" >A</text>\n  <rect  x="379.7" y="72.1156" width="83.16" height="18.3356" style="fill:#ffd802;"  />\n  <text x="421.28" y="85.8479" text-anchor="middle"  class="blackInkLetter_1" >U</text>\n  </g>\n\n </g>\n </svg>\n\n',
            chromograph_image_files: null,
            chromograph_prefixes: null,
            multiqc: null,
            cnv_report: null,
            coverage_qc_report: null,
            gene_fusion_report: 'scout/demo/draw-fusions-example.pdf',
            gene_fusion_report_research: null,
            vcf_files: {
              vcf_snv: 'scout/demo/643594.clinical.vcf.gz',
              vcf_sv: 'scout/demo/643594.clinical.SV.vcf.gz',
              vcf_str: 'scout/demo/643594.clinical.str.stranger.vcf.gz',
              vcf_cancer: null,
              vcf_cancer_sv: null,
              vcf_snv_research: 'scout/demo/643594.research.vcf.gz',
              vcf_sv_research: 'scout/demo/643594.research.SV.vcf.gz',
              vcf_cancer_research: null,
              vcf_cancer_sv_research: null,
            },
            delivery_report: 'scout/demo/delivery_report.html',
            has_svvariants: true,
            has_strvariants: true,
            is_migrated: false,
            track: 'rare',
            group: [],
            analysis_types: ['wes'],
            assignees: [],
            is_rerun: [],
            clinvar_variants: {},
            display_track: 'Rare Disease',
          },
        ],
      ],
      ['active', []],
      ['solved', []],
      ['archived', []],
    ],
    found_cases: 2,
    limit: 100,
  },
}
