version: "3"
services:
  scout:
    image: scout:latest      #v0.1
    volumes:
      - /home/nnorgren/scout/vault:/scout/vault:ro
    ports:
      - "5000:443"
    links:
      - scout-db
    environment:
      HOST: 0.0.0.0
      PORT: 443
      MONGO_HOST: scout-db
      MONGO_DBNAME: scout
      MONGO_PORT: 27017
      KEY_FILE: /scout/vault/key.pem
      CERT_FILE: /scout/vault/cert.pem
      CONF_FILE: /scout/vault/flask.config.py
    restart: always

  scout-db:
    image: mongo:4.0.10
    volumes:
      - /home/nnorgren/scout/database:/data/db
    restart: always

  scout-setup:
    image: scout-setup:v1.0
    restart: never
    links: 
      - scout-db
    environment:
      MONGO_HOST: scout-db
      MONGO_DBNAME: scout
      MONGO_PORT: 27017
      API_KEY: ReIWPEHwTxecrDFPZPrqyg

  scout-import:
    image: scout-import:v1.0
    volumes:
      - /home/nnorgren/scout/sampledata:/sampledata
    restart: never
    links:
      - scout-db
    environment:
      MONGO_HOST: scout-db
      MONGO_DBNAME: scout
      MONGO_PORT: 27017

  scout-remove:
    image: scout-remove:v1.0
    volumes:
      - /home/nnorgren/scout/sampledata:/sampledata
    restart: never
    links:
      - scout-db
    environment:
      MONGO_HOST: scout-db
      MONGO_DBNAME: scout
      MONGO_PORT: 27017

  scout-adduser:
    image: scout-adduser:v1.0
    links:
      - scout-db
    environment:
      MONGO_HOST: scout-db
      MONGO_DBNAME: scout
      MONGO_PORT: 27017

  scout-removeuser:
    image: scout-removeuser:v1.0
    links:
      - scout-db
    environment:
      MONGO_HOST: scout-db
      MONGO_DBNAME: scout
      MONGO_PORT: 27017

  scout-addpanel:
    image: scout-addpanel:v1.0
    links:
      - scout-db
    environment:
      MONGO_HOST: scout-db
      MONGO_DBNAME: scout
      MONGO_PORT: 27017

