FROM node:14.0.0-alpine

# create destination directory
RUN mkdir -p /app
WORKDIR /app

ENV PATH /react-modules/node_modules/.bin:$PATH

RUN apk update && apk upgrade
RUN apk add git

COPY package.json ./
COPY yarn.lock ./
RUN yarn install
COPY . .

EXPOSE 3000
CMD [ "yarn", "start" ]
