#!/usr/bin/env python
# encoding: utf-8
"""
scout

Script for using the scout tool

Created by Måns Magnusson on 2015-02-04.
Copyright (c) 2015 __TheScoutTeam__. All rights reserved.
"""

from __future__ import print_function, unicode_literals

import sys
import os
import click
import pkg_resources

from pprint import pprint as pp
from codecs import getwriter

from scout.commands import (load, wipe_and_load, wipe)

version = pkg_resources.require("scout")[0].version

def print_version(ctx, param, value):
    """Callback function for printing version and exiting
    Args:
        ctx (object) : Current context
        param (object) : Click parameter(s)
        value (boolean) : Click parameter was supplied or not
    Returns:
        None:
    """
    if not value or ctx.resilient_parsing:
        return
    click.echo('scout version: ' + version)
    ctx.exit()


###         This is the main script         ###

@click.group()
@click.option('--version',
                is_flag=True,
                callback=print_version,
                expose_value=False,
                is_eager=True
)
@click.option('-l', '--logfile',
                    type=click.Path(exists=False),
                    help="Path to log file. If none logging is "\
                          "printed to stderr."
)
@click.option('--loglevel',
                    type=click.Choice(['DEBUG', 'INFO', 'WARNING', 'ERROR', 
                                        'CRITICAL']),
                    help="Set the level of log output."
)
def cli(logfile, loglevel):
    """
    Tool for simulating structural variations.\n
    For more information, please run:
    svsim COMMAND --help \n
        """
    from scout import logger
    from scout.log import init_log
    init_log(logger, logfile, loglevel)

cli.add_command(load)
cli.add_command(wipe)
cli.add_command(wipe_and_load)

if __name__ == '__main__':
  print("HEJ")
  cli()
