---

name: Deploy release to production environment

on:
  workflow_dispatch:
    inputs:
      tag_name:
        description: 'Release tag'


jobs:
  create_deployment:
    runs-on: ubuntu-latest
    steps:
      - run: |
          curl \
            --fail \
            -X POST \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: token ${{ secrets.BUMPVERSION_TOKEN }}" \
            https://api.github.com/repos/${{ github.repository }}/deployments \
            -d '{
            "ref": "${{ github.event.inputs.tag_name }}",
            "environment": "production",
            "auto_merge": false,
            "description": "${{secrets.DEPLOYMENT_INFO}}"}'
