name: "Vulture - Find unused code"
on:
  - pull_request
jobs:
  build:
    runs-on: ubuntu-latest
    name: vulture
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Scavenge
        uses: anaynayak/python-vulture-action@v2
        id: vulture
        with:
          vulture-args: . --min-confidence 90
