name: vulture
on:
  - pull_request
jobs:
  vulture:
    runs-on: ubuntu-latest
    name: vulture
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Scavenge
        uses: anaynayak/python-vulture-action@v1
        id: vulture
        with:
          vulture-args: example --min-confidence 90
          fail-on-error: false
