name: "Vulture - Find unused code"
on:
  - pull_request
jobs:
  build:
    runs-on: ubuntu-latest
    name: vulture
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Vulture dependency
        run: |
            pip install vulture
      - name: Scavenge
        run: |
            vulture . --min-confidence 100
        fail-on-error: false
