name: "Vulture - Find unused code"
on:
  - pull_request
jobs:
  build:
    runs-on: ubuntu-latest
    name: vulture
    steps:
      - name: Checkout
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.8"
      - name: Scavenge
        uses: actions/python-vulture-action@v1
        id: vulture
        with:
          vulture-args: example --min-confidence 100
          fail-on-error: false
