name: "Changelog Reminder"
on:
  pull_request:
      types: [opened, synchronize, reopened, ready_for_review, labeled, unlabeled]

jobs:
  # Enforces the update of a changelog file on every pull request
  changelog:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Read version file
        id: get-version
        run: echo "version=$(cat __version__.py|sed -e 's/__version__ = "//; s/"//;')" >> $GITHUB_OUTPUT
    - uses: dangoslen/changelog-enforcer@v3
      with:
        changeLogPath: 'CHANGELOG.md'
        skipLabels: 'Skip-Changelog'
        expectedLatestVersion: ${{ steps.get-version.outputs.version }}
