name: Lint files and fix lint errors

# This will only correct linting in local PRs
on: ["push"]

jobs:
  build:

    name: Lint-and-fix
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7]

    steps:

    # Check out Scout code
    - name: Check out git repository
      uses: actions/checkout@v2

    # Set up python
    - name: Set up Python ${{ matrix.python-version}}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version}}

    - name: Install Python Dependencies
      run: |
        pip install black flake8

    - name: Run linters
      uses: samuelmeuli/lint-action@v1
      # Let linters fix problems if they can
      with:
        github_token: ${{ secrets.github_token }}
        auto_fix: true
        # Enable linters
        black: true
        black_args: "-l 100"
        # stop the build if there are Python syntax errors or undefined names
        flake8: true
        flake8_args: "scout/ --count --select=E9,F63,F7,F82 --show-source --statistics"
