name: Build and push Docker images
on:
  push:
    branches:
      - publish-container-dockerhub

jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: eriksjolund/scout
          tag_with_ref: true
          push: ${{ startsWith(github.ref, 'refs/tags/') }}
