
name: Pull request pipeline
on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Git checkout
      uses: actions/checkout@v1
    - name: Install
      run: yarn install
    - name: Run lint check
      run: yarn lint
    - name: Test
      run: yarn test