
name: Pull request pipeline
on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Git checkout
      uses: actions/checkout@v1
    - name: Install
      run: yarn install
    - name: Run lint check
      run: yarn lint
    - name: Test
      run: yarn test
  create_deployment:
    runs-on: ubuntu-latest
    steps:
      - run: |
          curl \
            --fail \
            -X POST \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: token ${{ secrets.BUMPVERSION_TOKEN }}" \
            https://api.github.com/repos/${{ github.repository }}/deployments \
            -d '{
            "ref": "${{ github.event.inputs.branch_name }}",
            "environment": "stage",
            "auto_merge": false,
            "description": "${{secrets.DEPLOYMENT_INFO}}"}'