
name: Pull request pipeline
on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Git checkout
      uses: actions/checkout@v1
    - name: Go to react-modules directory
      run: cd ./react-modules
    - name: Install
      run: yarn install
    - name: Run lint check
      run: yarn lint
    - name: Run stylelint check
      run: yarn stylelint
    - name: Test
      run: yarn test
    - name: Build Stage
      run: yarn build
      env:
        GOOGLE_OAUTH_CLIENT_ID: 'id'
        BACKEND_URL: 'none'
        MOCK: false
