name: Master pipeline

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout to master
      uses: actions/checkout@master
    - name: Install
      run: yarn install
    - name: Run lint check
      run: yarn lint
    - name: Test
      run: yarn test
    - name: Build Stage
      run: yarn build
      env:
          GOOGLE_OAUTH_CLIENT_ID: 'id'
          BACKEND_URL: 'none'
          MOCK: false
