
name: Pull request pipeline
on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Git checkout
      uses: actions/checkout@v1
    - name: Install
      working-directory: ./react-modules
      run: yarn install
    - name: Run lint check
      working-directory: ./react-modules
      run: yarn lint
    - name: Run stylelint check
      working-directory: ./react-modules
      run: yarn stylelint
    - name: Test
      working-directory: ./react-modules
      run: yarn test
    - name: Build Stage
      working-directory: ./react-modules
      run: yarn build
      env:
        GOOGLE_OAUTH_CLIENT_ID: 'id'
        BACKEND_URL: 'none'
        MOCK: false
